import clsx from 'clsx';
import { AuthSync } from 'modules/auth/ui/auth-sync';
import { AlertProvider } from 'modules/conversation/messages-chat/hooks/use-alert';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import { JSX, ReactNode } from 'react';
import { QueryProvider } from 'shared/query/query-provider';
import '../shared/styles/globals.scss';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600'],
  display: 'swap',
});

const sfPro = localFont({
  src: [{ path: '../fonts/sf-pro/SFProDisplay-Bold.woff2', weight: '1000', style: 'normal' }],
  variable: '--font-sf-pro',
});

export const metadata: Metadata = {
  title: 'Мессенджер (А-чат) 5 отдел',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={clsx(roboto.variable, sfPro.variable)}>
        <QueryProvider>
          <AlertProvider>
            <AuthSync />
            {children}
          </AlertProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
